### ISSUE TITLE
projection_stereographic is missing

### ISSUE THREAD

**Issue by Gaorion** [skybber/fchart3#5]
Hello,

Projection_stereographic is missing 
i comment the line in the __init__.py and it work.

version='0.9.0'

from .config_loader import *
from .skymap_engine import *
from .configuration import *
from .used_catalogs import *
from .graphics_cairo import *
from .graphics_skia import *
from .graphics_tikz import *
from .graphics_interface import *
from .highlight_definition import *
from .dso_highlight_definition import *
from .projection_interface import *
from .projection_orthographic import *
#from .projection_stereographic import *

**Comment by skybber** [comment]
Thanks for the feedback, I fixed it. I hope you like fchart3!
